public class testformula{
   public static testMethod void ans(){
     decimal a, b, c;
      formula ans = new formula();
      ans.getValues();
      ans.setValues(2,3,1);
      //ans.getValues();
      ans.res1();
      ans.res2();
      system.debug('...................................');
      system.debug('...................................');
      system.debug('...................................');
      ans.setValues(2,3,6);
      ans.res1();
      ans.res2();
   }



}